# Generated by Django 3.2.13 on 2023-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0018_user2tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curuserweisum',
            field=models.IntegerField(default=0),
        ),
    ]
