# Generated by Django 2.2.27 on 2023-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0020_auto_20230523_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2tag',
            name='weight',
            field=models.IntegerField(default=65535),
        ),
    ]
