# Generated by Django 2.2.27 on 2023-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0021_auto_20230523_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='curuserweisum',
            field=models.IntegerField(default=65535),
        ),
        migrations.AlterField(
            model_name='user2tag',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
