# 这个文件包含了项目的最基本的配置信息，包括数据库、路由、文件路径设置等等

"""
Django settings for xiaotuan project.

Generated by 'django-admin startproject' using Django 2.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


SECRET_KEY = '5&+*9!=y=-p0*!878o7f+m+9ss-q3u5$*@&hz3wp!4b3fw%xg6'

DEBUG = True

ALLOWED_HOSTS = ['*']


# 对APP应用的添加，上面的是django自带的app，tuanzi与dailyreport是我们自己建立的app
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tuanzi',
    'dailyreport',
]

# 对中间件的添加
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xiaotuan.urls'


#这里为templates的目录进行了定义
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xiaotuan.wsgi.application'


# 这里对数据库进行了定义，注意在不同的环境下运行，需要不同的数据库设置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tuanzi',
        'USER': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
        'PASSWORD': 'root',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "tuanzi.UserInfo" 


LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True




# 这里对静态资源文件进行了定义
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    (os.path.join(BASE_DIR,'static')),
]

MEDIA_ROOT=os.path.join(BASE_DIR,"media")
MEDIA_URL='/media/'
LOGIN_URL = '/login/'
EMAIL_HOST = 'smtp.exmail.qq.com'  
EMAIL_PORT = 465
EMAIL_HOST_USER = ''          
EMAIL_HOST_PASSWORD = ''  
EMAIL_USE_SSL = True